config/routes.rb
Rails.application.routes.draw do

  resources :labs, :path => "laboratorios"
  resources :incomings, :path => "ingresos"
  resources :vacunas
  resources :products
  resources :type_products
  devise_for :users
  resources :veterinaries, :path => "veterinarios"  
  resources :services, :path => "servicios"  
  resources :type_services, :path => "tipo_servicios"   
  resources :internships, :path => "hospitalizaciones"  
  resources :pets, :path => "mascotas"  
  resources :clients, :path => "clientes"  
  root 'static_pages#home'
  get 'admin/users' => 'admin#convert'
  get 'admin/users_convert/:id' => 'admin#convert_almacen'
  get 'mascotas/servicio/:id' => 'pets#service'
  get '/mascotas/vacuna/:id' => 'pets#vacuna'
  post 'mascotas/servicio/save' => 'pets#saveService'
  post 'mascotas/vacuna/save' => 'pets#saveVacuna'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :pets
end

app/models/incoming.rb
class Incoming < ApplicationRecord
end

app/models/internship.rb
class Internship < ApplicationRecord
  belongs_to :pet
end

app/models/lab.rb
class Lab < ApplicationRecord
  belongs_to :pet
	has_attached_file :imagen
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :client
  has_many :internships
  has_many :registers
  has_many :vacunas 
  has_many :labs

  has_attached_file :imagen
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/
  def dischargeDate
  	date = Time.now.to_date
  	if self.internships.size > 0
  		date = self.internships.last.dischargeDate
  	end
  	date
  end
end

app/models/pet_has_vacuna.rb
class PetHasVacuna < ApplicationRecord
  belongs_to :vacuna
  belongs_to :pet
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :type_product
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :veterinary
  belongs_to :service
  belongs_to :pet
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :registers
end

app/models/type_product.rb
class TypeProduct < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role

  before_validation :isAdmin, on: :create

  private
  def isAdmin
  	if User.all.size < 1
    	self.role_id = Role.first.id
    else
    	self.role_id = Role.last.id
    end
  end

end

app/models/vacuna.rb
class Vacuna < ApplicationRecord
	has_many :pet_has_vacunas
	has_many :pets
end

app/models/veterinary.rb
class Veterinary < ApplicationRecord
	has_many :registers
end

app/controllers/vacunas_controller.rb
class VacunasController < ApplicationController
  before_action :set_vacuna, only: [:show, :edit, :update, :destroy]

  # GET /vacunas
  # GET /vacunas.json
  def index
    @vacunas = Vacuna.all
  end

  # GET /vacunas/1
  # GET /vacunas/1.json
  def show
  end

  # GET /vacunas/new
  def new
    @vacuna = Vacuna.new
  end

  # GET /vacunas/1/edit
  def edit
  end

  # POST /vacunas
  # POST /vacunas.json
  def create
    @vacuna = Vacuna.new(vacuna_params)

    respond_to do |format|
      if @vacuna.save
        format.html { redirect_to @vacuna, notice: 'Vacuna was successfully created.' }
        format.json { render :show, status: :created, location: @vacuna }
      else
        format.html { render :new }
        format.json { render json: @vacuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacunas/1
  # PATCH/PUT /vacunas/1.json
  def update
    respond_to do |format|
      if @vacuna.update(vacuna_params)
        format.html { redirect_to @vacuna, notice: 'Vacuna was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacuna }
      else
        format.html { render :edit }
        format.json { render json: @vacuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacunas/1
  # DELETE /vacunas/1.json
  def destroy
    @vacuna.destroy
    respond_to do |format|
      format.html { redirect_to vacunas_url, notice: 'Vacuna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacuna
      @vacuna = Vacuna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacuna_params
      params.require(:vacuna).permit(:name, :detail)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/vacunas_helper.rb
module VacunasHelper
end

app/views/vacunas/_form.html.erb
<%= form_with(model: vacuna, local: true) do |form| %>
  <% if vacuna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacuna.errors.count, "error") %> prohibited this vacuna from being saved:</h2>

      <ul>
      <% vacuna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :name, id: :vacuna_name %>
  </div>

  <div class="field">
    <%= form.label :detalle %>
    <%= form.text_area :detail, id: :vacuna_detail %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar"%>
  </div>
<% end %>

app/views/vacunas/edit.html.erb
<h1>Editar Vacuna</h1>

<%= render 'form', vacuna: @vacuna %>

<%= link_to 'Mostrar', @vacuna %> |
<%= link_to 'Atras', vacunas_path %>

app/views/vacunas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacunas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Detalle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacunas.each do |vacuna| %>
      <tr>
        <td><%= vacuna.name %></td>
        <td><%= vacuna.detail %></td>
        <td><%= link_to 'Mostrar', vacuna %></td>
        <td><%= link_to 'Editar', edit_vacuna_path(vacuna) %></td>
        <td><%= link_to 'Eliminar', vacuna, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Vacuna', new_vacuna_path %>

app/views/vacunas/new.html.erb
<h1>Nueva Vacuna</h1>

<%= render 'form', vacuna: @vacuna %>

<%= link_to 'Atras', vacunas_path %>

app/views/vacunas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @vacuna.name %>
</p>

<p>
  <strong>Detalle:</strong>
  <%= @vacuna.detail %>
</p>

<%= link_to 'Editar', edit_vacuna_path(@vacuna) %> |
<%= link_to 'Atras', vacunas_path %>